language: php
php:
- 5.6
- 5.5
- 7.0
install:
- composer install
env:
  global:
    - APP_ENV=testing
    - APP_KEY=M0HYKpEoPSPnl7V4Ck6notarealkeyUx
before_script:
  - touch /home/travis/build/TwilioDevEd/employee-directory-laravel/storage/app/database.sqlite
  - php artisan migrate
  - php artisan db:seed
  